### ISSUE TITLE
ImportError: No module named "AKU"

### ISSUE THREAD

**Issue by lihaochen910** [tommo/gii#1]
OS: Win10_x64
PythonVer: 2.7_x64
MoaiSDK: 1.7.5 (from [moai-community](https://github.com/moai/moai-community))

我对你的Gii编辑器辑器很感兴趣
我尝试在Windows平台打开Gii IDE，得到了一些错误
```
PS D:\gii> python .\gii_bin.py ide
Traceback (most recent call last):
  File ".\gii_bin.py", line 81, in <module>
    main()
  File ".\gii_bin.py", line 76, in main
    gii.startup()
  File "D:\gii/lib\gii\__init__.py", line 6, in startup
    startupTool( info )
  File "D:\gii/lib\gii\core\tool.py", line 170, in startupTool
    return startTool( toolInfo )
  File "D:\gii/lib\gii\core\tool.py", line 90, in startTool
    m.main( sys.argv[ 1: ] )
  File "D:\gii\tools/ide/__init__.py", line 28, in main
    return run( argv[1:], 'gii ide' )
  File "D:\gii/lib/3rdparty/common\click\core.py", line 719, in __call__
    return self.main(*args, **kwargs)
  File "D:\gii/lib/3rdparty/common\click\core.py", line 699, in main
    rv = self.invoke(ctx)
  File "D:\gii/lib/3rdparty/common\click\core.py", line 892, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\gii/lib/3rdparty/common\click\core.py", line 527, in invoke
    return callback(*args, **kwargs)
  File "D:\gii\tools/ide/__init__.py", line 14, in run
    import gii.SceneEditor
  File "D:\gii/lib\gii\SceneEditor\__init__.py", line 2, in <module>
    from SceneEditor import SceneEditor, SceneEditorModule, getSceneSelectionManager
  File "D:\gii/lib\gii\SceneEditor\SceneEditor.py", line 19, in <module>
    from gii.moai.MOAIRuntime import MOAILuaDelegate
  File "D:\gii/lib\gii\moai\__init__.py", line 1, in <module>
    from MOAIRuntime     import  MOAIRuntime, MOAILuaDelegate, _G, LuaTableProxy, _LuaTable, _LuaThread, _LuaObject, _LuaFunction
  File "D:\gii/lib\gii\moai\MOAIRuntime.py", line 7, in <module>
    from AKU import getAKU, _LuaTable, _LuaThread, _LuaObject, _LuaFunction
ImportError: No module named AKU
```
提示AKU模块未找到，
谷歌了一下发现AKU模块好像需要将moai构建为[moaipy模块](https://github.com/Vavius/moai-ide)

我又尝试构建moaipy模块，报错提示[找不到标识符](https://github.com/Vavius/moai-ide/issues/2)
```
moaipy.cpp(18273): error C3861: “AKURunScript”: 找不到标识符
moaipy.cpp(18324): error C3861: “AKURunString”: 找不到标识符
moaipy.cpp(18569): error C3861: “AKUReleaseGfxContext”: 找不到标识符
moaipy.cpp(18960): error C3861: “AKUSoftReleaseGfxResources”: 找不到标识符
moaipy.cpp(20638): error C3861: “AKUEnqueueKeyboardAltEvent”: 找不到标识符
moaipy.cpp(20750): error C3861: “AKUEnqueueKeyboardControlEvent”: 找不到标识符
moaipy.cpp(20873): error C3861: “AKUEnqueueKeyboardEvent”: 找不到标识符
moaipy.cpp(20985): error C3861: “AKUEnqueueKeyboardShiftEvent”: 找不到标识符
moaipy.cpp(22058): error C2065: “AKU_DATA_STRING”: 未声明的标识符
moaipy.cpp(22058): error C3861: “AKURunData”: 找不到标识符
```
你是否也遇到过这个问题？求编译moaipy的正确姿势，，

**Comment by tommo** [comment]
不好意思，这个项目现在还是内部状态。之前建了这个仓库也是给远程合作的人用的。编辑器要公开还需要不少准备，但要等手上的游戏完成后才会有时间了。

**Comment by lihaochen910** [comment]
编辑器代码对于我这个初学者来说真是收益匪浅的
nice job！

**Comment by rekcah1986** [comment]
考古，我也卡在这里了，话说python的环境真是无语

**Comment by lihaochen910** [comment]
@rekcah1986 我自行编译了AKU，步骤特别麻烦，你什么平台的，我可以发你编译好的二进制可以直接加载
[AKU_Python38.zip](https://github.com/tommo/gii/files/7474465/AKU_Python38.zip)

**Comment by rekcah1986** [comment]
@lihaochen910 好人一生平安
